### ISSUE TITLE
Image.Width and Height are 0 when using Image(byte[],string)

### ISSUE THREAD

**Issue by optlink** [CodeComb/Media#2]
If I try to run the following code, where image is some instance of `byte[]` containing a PNG:

```
var test = new CodeComb.Media.Image(image,".png");
Console.WriteLine(test.Width.ToString() + ',' + test.Height.ToString()); 
```

I get 0,0 in the output. The image will convert just fine though.

**Comment by yukozh** [comment]
Which version are you using? @optlink

**Comment by optlink** [comment]
2.0.0-beta8

**Comment by yukozh** [comment]
Ok, I will back you later.

**Comment by yukozh** [comment]
@optlink Which target are you using? DNX451, DNXCORE50 or .Net 4.5?

**Comment by optlink** [comment]
DNXCORE50

**Comment by yukozh** [comment]
Confirmed a bug. I will release beta8-2 today.

**Comment by yukozh** [comment]
@optlink https://www.nuget.org/packages/CodeComb.media/2.0.0-beta8-2

**Comment by optlink** [comment]
Thanks for the quick fix

**Comment by yukozh** [comment]
![image](https://cloud.githubusercontent.com/assets/2216750/11109422/2e443a12-892b-11e5-80b8-68f2da4bb22d.png)

It works well with my computer now.

:smile:

**Comment by yukozh** [comment]
CodeComb.Media also avaliable for dnx rc1/rc2 on https://www.myget.org/gallery/codecomb

Thanks for catching this bug.
